# --- !Ups

ALTER TABLE users MODIFY COLUMN first_name VARCHAR(200) NOT NULL;
ALTER TABLE users MODIFY COLUMN last_name VARCHAR(200) NOT NULL;

# --- !Downs

ALTER TABLE users MODIFY COLUMN first_name VARCHAR(45) NOT NULL;
ALTER TABLE users MODIFY COLUMN last_name VARCHAR(45) NOT NULL;