# --- !Ups

ALTER TABLE users MODIFY COLUMN state_name VARCHAR(30) NULL;
ALTER TABLE users MODIFY COLUMN country_name VARCHAR(30) NULL;
ALTER TABLE users MODIFY COLUMN city_name VARCHAR(80) NULL;

# --- !Downs

ALTER TABLE users MODIFY COLUMN state_name VARCHAR(30) NOT NULL;
ALTER TABLE users MODIFY COLUMN country_name VARCHAR(30) NOT NULL;
ALTER TABLE users MODIFY COLUMN city_name VARCHAR(80) NOT NULL;